# Get Users
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic2FiaWxAZ21haWwuY29tIiwibmFtZSI6InNhYmlsIiwiaWF0IjoxNjg1NTk5Nzk5LCJleHAiOjE2ODU2ODYxOTl9.fvH_0V4yNNx4L19GUnlpcd_wcmMM1SAOkUFrYdP7FZU
###

# Register
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "sabil",
    "email": "sabil@gmail.com",
    "password": "54321",
    "confPassword": "54321"
}

###

# Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "sabil@gmail.com",
    "password": "password" 
}

###

# Refresh Token
GET http://localhost:5000/token

###

# Update Profile
PUT http://localhost:5000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic2FiaWxAZ21haWwuY29tIiwibmFtZSI6InNhYmlsIiwiaWF0IjoxNjg1NTk5Nzk5LCJleHAiOjE2ODU2ODYxOTl9.fvH_0V4yNNx4L19GUnlpcd_wcmMM1SAOkUFrYdP7FZU
Content-Type: application/json

{
  "gender": "female",
  "weight": 50,
  "height": 165
}

###

# Change Password
PUT http://localhost:5000/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic2FiaWxAZ21haWwuY29tIiwibmFtZSI6InNhYmlsIiwiaWF0IjoxNjg1NTk5Nzk5LCJleHAiOjE2ODU2ODYxOTl9.fvH_0V4yNNx4L19GUnlpcd_wcmMM1SAOkUFrYdP7FZU
Content-Type: application/json

{
  "currentPassword": "54321",
  "newPassword": "password",
  "reenterPassword": "password"
}


###

# Logout
DELETE http://localhost:5000/logout
